# docker-compose.prod.yml
version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn gamma.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:8000
    depends_on:
      - web


